[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_assertions = "1.4.1"
rand = "0.8.5"
termion = "4.0.2"
# rusty_check = {git = "https://github.com/jkszymczak/RustyCheck.git"}
rusty_check = {path = "../RustyCheck/rusty_check"}